"use strict";

/**
 * Module dependencies.
 */
var mongoose = require('mongoose'),
    moment = require('moment'),
    Schema = mongoose.Schema,
    ObjectId = mongoose.Schema.Types.ObjectId,
    timestamps = require('mongoose-timestamp');

var DataTable = require('mongoose-datatable');

DataTable.configure({
    verbose: false,
    debug: false
});
mongoose.plugin(DataTable.init);

var Dict = INCLUDE('dict');

var setPrice = MODULE('utils').setPrice;
var setDate = MODULE('utils').setDate;

/**
 * Article Schema
 */
var billSchema = new Schema({
    forSales: { type: Boolean, default: true },
    ref: { type: String, index: true },
    isremoved: Boolean,
    ID: { type: Number },
    /*title: {//For internal use only
     ref: String,
     autoGenerated: {type: Boolean, default: false} //For automatic process generated bills
     },*/
    currency: {
        _id: { type: String, ref: 'currency', default: '' },
        rate: { type: Number, default: 1 } // changed default to '0' for catching errors
    },
    Status: { type: String, default: 'DRAFT' },
    cond_reglement_code: {
        type: String,
        default: 'RECEP'
    },
    mode_reglement_code: {
        type: String,
        default: 'TIP'
    },
    //bank_reglement: {type: String},
    //availability_code: {type: String, default: 'AV_NOW'},
    type: {
        type: String,
        default: 'SRC_COMM'
    },
    supplier: { type: Schema.Types.ObjectId, ref: 'Customers' },
    contacts: [{ type: Schema.Types.ObjectId, ref: 'Customers' }],
    ref_client: { type: String, default: "" },

    imported: { type: Boolean, default: false }, //imported in accounting
    journalId: [Schema.Types.ObjectId], // Id transactions for accounting

    orders: [{ type: Schema.Types.ObjectId, ref: 'order' }],

    datec: { type: Date, default: new Date, set: setDate },
    dater: { type: Date, set: setDate }, // date limit reglement
    dateOf: { type: Date }, // Periode de facturation du
    dateTo: { type: Date }, // au
    notes: [{
        title: String,
        note: String,
        public: {
            type: Boolean,
            default: false
        },
        edit: {
            type: Boolean,
            default: false
        }
    }],
    discount: {
        escompte: {
            percent: { type: Number, default: 0 },
            value: { type: Number, default: 0, set: setPrice } // total remise globale
        },
        discount: {
            percent: { type: Number, default: 0 }, //discount
            value: { type: Number, default: 0, set: setPrice } // total remise globale
        }
    },
    total_ht: {
        type: Number,
        default: 0,
        set: setPrice
    },
    total_taxes: [{
        _id: false,
        taxeId: { type: Schema.Types.ObjectId, ref: 'taxes' },
        value: { type: Number, default: 0 }
    }],
    total_ttc: { type: Number, default: 0, set: setPrice },
    total_paid: { type: Number, default: 0, set: setPrice },
    shipping: {
        total_ht: {
            type: Number,
            default: 0,
            set: setPrice
        },
        total_taxes: [{
            _id: false,
            taxeId: { type: Schema.Types.ObjectId, ref: 'taxes' },
            value: { type: Number, default: 0 }
        }],
        /*total_ttc: {
            type: Number,
            default: 0
        }*/
    },
    createdBy: { type: ObjectId, ref: 'Users', default: null },
    editedBy: { type: ObjectId, ref: 'Users', default: null },
    salesPerson: { type: ObjectId, ref: 'Employees', default: null }, //commercial_id
    salesTeam: { type: ObjectId, ref: 'Department', default: null },
    entity: String,
    optional: Schema.Types.Mixed,
    delivery_mode: { type: String, default: "Comptoir" },
    billing: { type: Schema.Types.ObjectId, ref: 'Customers' },
    //costList: { type: ObjectId, ref: 'priceList', default: null }, //Not used
    //priceList: { type: ObjectId, ref: 'priceList', default: null },

    address: {
        name: { type: String, default: '' },
        street: { type: String, default: '' },
        city: { type: String, default: '' },
        state: { type: String, default: '' },
        zip: { type: String, default: '' },
        country: { type: String, ref: 'countries', default: 'FR' }
    },
    shippingAddress: {
        _id: { type: ObjectId, default: null },
        name: { type: String, default: '' },
        street: { type: String, default: '' },
        city: { type: String, default: '' },
        state: { type: String, default: '' },
        zip: { type: String, default: '' },
        country: { type: String, ref: 'countries', default: 'FR' }
    },
    /*bl: [{
        label: String,
        name: String,
        contact: String,
        address: String,
        zip: String,
        town: String,
        products: [{
            id: Schema.Types.ObjectId,
            name: String,
            qty: {
                type: Number,
                default: 0
            } // QTY Order
        }],
        shipping: {
            id: String,
            label: String,
            address: Boolean,
            total_ht: {
                type: Number,
                default: 0
            }
        }
    }],*/
    weight: { type: Number, default: 0 }, // Poids total
    lines: [{
        _id: false,
        //pu: {type: Number, default: 0},
        type: { type: String, default: 'product' }, //Used for subtotal
        qty: { type: Number, default: 0 },
        /*taxes: [{
            _id: false,
            taxeId: { type: Schema.Types.ObjectId, ref: 'taxes' },
            value: { type: Number }
        }],*/
        //price_base_type: String,
        //title: String,
        priceSpecific: { type: Boolean, default: false },
        pu_ht: {
            type: Number,
            default: 0
        },
        description: String,
        private: String, // Private note
        product_type: String,
        product: { type: Schema.Types.ObjectId, ref: "product" },
        total_taxes: [{
            _id: false,
            taxeId: { type: Schema.Types.ObjectId, ref: 'taxes' },
            value: { type: Number }
        }],
        /*total_ttc: {
            type: Number,
            default: 0
        },*/
        discount: { type: Number, default: 0 },
        total_ht: { type: Number, default: 0, set: setPrice },
        //weight: { type: Number, default: 0 },
        optional: { type: Schema.Types.Mixed }
    }],
    history: [{
        date: { type: Date, default: Date.now },
        author: {
            id: String,
            name: String
        },
        mode: String, //email, order, alert, new, ...
        Status: String,
        msg: String
    }],
    //feeBilling: { type: Boolean, default: true }, // Frais de facturation
    oldId: String // Only for import migration
}, {
    toObject: { virtuals: true },
    toJSON: { virtuals: true }
});

billSchema.plugin(timestamps);

// Gets listing
billSchema.statics.query = function(options, callback) {
    var self = this;

    // options.query {}
    // options.fileds {String}
    // options.page {String or Number}
    // options.max {String or Number}
    // options.id {String}

    options.page = U.parseInt(options.page) - 1;
    options.max = U.parseInt(options.max, 20);
    if (options.id && typeof(options.id) === 'string')
        options.id = options.id.split(',');
    if (options.page < 0)
        options.page = 0;
    var take = U.parseInt(options.max);
    var skip = U.parseInt(options.page * options.max);

    var query = options.query;
    if (!query.isremoved)
        query.isremoved = { $ne: true };

    //if (options.search)
    //    builder.in('search', options.search.keywords(true, true));
    if (options.id) {
        if (typeof options.id === 'object')
            options.id = { '$in': options.id };
        query._id = options.id;
    }

    var sort = "ref";

    if (options.sort)
        sort = options.sort;

    //console.log(query);

    this.find(query)
        .select(options.fields)
        .limit(take)
        .skip(skip)
        //.populate('category', "_id path url linker name")
        .sort(sort)
        //.lean()
        .exec(function(err, doc) {
            //console.log(doc);
            var data = {};
            data.count = doc.length;
            data.items = doc;
            data.limit = options.max;
            data.pages = Math.ceil(data.count / options.max);

            if (!data.pages)
                data.pages = 1;
            data.page = options.page + 1;
            callback(null, data);
        });
};

/**
 * Pre-save hook
 */
billSchema.pre('save', function(next) {

    var self = this;
    var SeqModel = MODEL('Sequence').Schema;
    var EntityModel = MODEL('entity').Schema;

    this.dater = MODULE('utils').calculate_date_lim_reglement(this.datec, this.cond_reglement_code);

    if (this.isNew)
        this.history = [];

    MODULE('utils').sumTotal(this.lines, this.shipping, this.discount, this.supplier, function(err, result) {
        if (err)
            return next(err);

        self.total_ht = result.total_ht;
        self.total_taxes = result.total_taxes;
        self.total_ttc = result.total_ttc;
        self.weight = result.weight;

        if (self.total_ttc === 0)
            self.Status = 'DRAFT';

        if (!self.ref && self.isNew)
            return SeqModel.inc("PROV", function(seq, number) {
                //console.log(seq);
                self.ID = number;
                self.ref = "PROV" + seq;
                next();
            });

        if (self.Status != "DRAFT" && self.total_ttc != 0 && self.ref.substr(0, 4) == "PROV") {
            if (self.forSales == true)
                return SeqModel.inc("INVOICE", function(seq, number) {
                    //console.log(seq);
                    self.ID = number;
                    EntityModel.findOne({
                        _id: self.entity
                    }, "cptRef", function(err, entity) {
                        if (err)
                            console.log(err);

                        if (entity && entity.cptRef)
                            self.ref = (self.total_ttc < 0 ? "AV" : "FA") + entity.cptRef + seq;
                        else
                            self.ref = (self.total_ttc < 0 ? "AV" : "FA") + seq;
                        next();
                    });
                });

            //supplier invoice
            return SeqModel.inc("SUPPLIER_INVOICE", function(seq, number) {
                //console.log(seq);
                self.ID = number;
                EntityModel.findOne({
                    _id: self.entity
                }, "cptRef", function(err, entity) {
                    if (err)
                        console.log(err);

                    if (entity && entity.cptRef)
                        self.ref = "FF" + entity.cptRef + seq;
                    else
                        self.ref = "FF" + seq;
                    next();
                });
            });
        }

        self.ref = F.functions.refreshSeq(self.ref, self.datec);
        next();
    });
});

/*var statusList = {};
Dict.dict({ dictName: 'fk_bill_status', object: true }, function(err, doc) {
    if (err) {
        console.log(err);
        return;
    }
    statusList = doc;
});*/

exports.Status = {
    "_id": "fk_bill_status",
    "lang": "bills",
    "values": {
        "DRAFT": {
            "enable": true,
            "label": "BillStatusDraft",
            "cssClass": "ribbon-color-default label-default",
            "system": true
        },
        "VALIDATED": {
            "enable": true,
            "label": "BillStatusValidated",
            "cssClass": "ribbon-color-success label-success"
        },
        "NOT_PAID": {
            "enable": true,
            "label": "BillStatusNotPaid",
            "cssClass": "ribbon-color-danger label-danger",
            "system": true
        },
        "PAID": {
            "enable": true,
            "label": "BillShortStatusPaid",
            "cssClass": "ribbon-color-success label-success",
            "system": true
        },
        "PAID_PARTIALLY": {
            "enable": true,
            "label": "BillStatusClosedPaidPartially",
            "cssClass": "ribbon-color-info label-info",
            "system": true
        },
        "CANCELED": {
            "enable": true,
            "label": "BillStatusCanceled",
            "cssClass": "ribbon-color-warning label-warning",
            "system": true
        },
        "CONVERTED_TO_REDUC": {
            "enable": true,
            "label": "BillStatusConvertedToReduc",
            "cssClass": "ribbon-color-success label-success",
            "system": true
        },
        "PAID_BACK": {
            "enable": true,
            "label": "BillShortStatusPaid",
            "cssClass": "ribbon-color-success label-success",
            "system": true
        }
    }
};

billSchema.virtual('status')
    .get(function() {
        var res_status = {};

        var status = this.Status;
        var statusList = exports.Status;

        if (status === 'NOT_PAID' && this.dater > moment().subtract(10, 'days').toDate()) //Check if late
            status = 'VALIDATE';

        if (status && statusList.values[status] && statusList.values[status].label) {
            //console.log(this);
            res_status.id = status;
            res_status.name = i18n.t(statusList.lang + ":" + statusList.values[status].label);
            //res_status.name = statusList.values[status].label;
            res_status.css = statusList.values[status].cssClass;
        } else { // By default
            res_status.id = status;
            res_status.name = status;
            res_status.css = "";
        }
        return res_status;

    });

/*var transactionList = [];
 
 TransactionModel.aggregate([
 {$group: {
 _id: '$bill.id',
 sum: {$sum: '$credit'}
 }}
 ], function (err, doc) {
 if (err)
 return console.log(err);
 
 transactionList = doc;
 });*/

billSchema.virtual('amount').get(function() {

    var amount = {};
    var id = this._id;



    /*if (transactionList) {
     for (var i = 0; i < transactionList.length; i++) {
     if (id.equals(transactionList[i]._id)) {
     amount.rest = this.total_ttc - transactionList[i].sum;
     amount.set = transactionList[i].sum;
     return amount;
     }
     }
     }*/

    return this.total_ttc - this.total_paid;
});


exports.Schema = mongoose.model('bill', billSchema, 'Invoices');
exports.name = 'bill';